---
### Site settings
### Access via {{ site.title }}, {{ site.email }}, and so on.

### Site variables
title: L. Gloege
name: Luke Gloege
email: gloege@ldeo.columbia.edu
github: https://github.com/lgloege
vimeo: https://vimeo.com/user64960926
description: ""
#baseurl: "/lgloege.github.io"
#url: "http://lgloege.github.io"

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed

### Sass settings
sass:
  sass_dir: _sass

# Bibliography settings
scholar:
  style: apa
  locale: en
  sort_by: year
  order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  query: "@*"

# Exclude from processing.
# The following items will not be processed
# exclude:
#   - README.md
#   - Gemfile
#   - Gemfile.lock
#   - package.json
#   - package-lock.json
#   - node_modules
---
